### ISSUE TITLE
Please add a license file and screen shot

### ISSUE THREAD

**Issue by unixorn** [alexchmykhalo/superconsole#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add tutorials with screen shots in the readme so that users can see what their console will look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by alexchmykhalo** [comment]
@unixorn I've added screenshot and LICENSE.txt.
