### ISSUE TITLE
Issue with set_conemu_cwd when the path has spaces

### ISSUE THREAD

**Issue by oleksandrlynda** [alexchmykhalo/superconsole#4]
Have this error: `set_conemu_cwd: no such file or directory: /d/Projects/Hands` where the path is cut.

**Comment by oleksandrlynda** [comment]
Also, the error is appearing all the time when I use commands like cd, ls, etc.

**Comment by alexchmykhalo** [comment]
Could not reproduce an issue with the latest build.
