### ISSUE TITLE
Will this work for us?

### ISSUE THREAD

**Issue by N6REJ** [alexchmykhalo/superconsole#5]
Hello, We're looking for a replacement for our portable *ampp stack module "consolez".
https://github.com/Bearsampp/module-consolez
Can superconsole be such a replacement?
What exactly would we need to do to do so?
When its open and you see the icon in the task bar is that icon configurable?
Thanks in advance

**Comment by alexchmykhalo** [comment]
Well, Supeconsole is NOT a unique software solution. It's just a collection of existing software projects bundled together.
All (almost) the software inside is provided by MSYS2 project. You could have a general overview here: https://www.msys2.org/ and see list of available packages here: https://packages.msys2.org/queue.

As a terminal app, it uses ConEmu (https://conemu.github.io/). ConEmu does not work perfectly with zsh provided by MSYS2. With some settings, various issues with shell prompt, and output and some apps with non-GUI interface may appear.  

Anything else is just custom config files and zsh customizations (oh-my-zsh project, agkozak zsh theme). All that files you can find in a repo, as well as steps that I perform to place config files in proper locations and preinstall some MSYS2 software. (see https://github.com/alexchmykhalo/superconsole/blob/master/build.cmd).

So, If you think that the software projects above will suit your needs - you could use them directly. And use this repo as a possible example / reference point on how it could work together.
